stages:
  - Publish

Publish Node.js:
  image: node:14
  stage: Publish
  script:
    - sh create-settings.sh
    - npm install
    - npm run build
    - npm publish --registry=${NEXUS_REGISTRY_URL}
  rules:
    - if: '$CI_COMMIT_BRANCH == "Devops-temp" && $NEXUS_OSSRH_UPLOAD'
      changes:
        - "*[^.md]"
